// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllProcesses() {
  return window['go']['pkg']['App']['GetAllProcesses']();
}

export function GetAllUsers() {
  return window['go']['pkg']['App']['GetAllUsers']();
}

export function GetCronTasks() {
  return window['go']['pkg']['App']['GetCronTasks']();
}

export function GetLoginSuccessRecords() {
  return window['go']['pkg']['App']['GetLoginSuccessRecords']();
}

export function GetNetworkConnections() {
  return window['go']['pkg']['App']['GetNetworkConnections']();
}

export function GetNetworkInfo() {
  return window['go']['pkg']['App']['GetNetworkInfo']();
}

export function GetPatchInfo() {
  return window['go']['pkg']['App']['GetPatchInfo']();
}

export function GetStartupItems() {
  return window['go']['pkg']['App']['GetStartupItems']();
}

export function GetSystemInfo() {
  return window['go']['pkg']['App']['GetSystemInfo']();
}

export function GetUserInfo() {
  return window['go']['pkg']['App']['GetUserInfo']();
}
