// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pkg} from '../models';

export function GetAllProcesses():Promise<Array<pkg.ProcInfo>>;

export function GetAllUsers():Promise<Array<pkg.SystemUser>>;

export function GetCronTasks():Promise<Array<pkg.CronTask>>;

export function GetLoginFailedRecords():Promise<Array<pkg.LoginFailed>>;

export function GetLoginSuccessRecords():Promise<Array<pkg.LoginSuccess>>;

export function GetNetworkConnections():Promise<Array<pkg.NetworkConn>>;

export function GetNetworkInfo():Promise<pkg.NetworkInfo>;

export function GetRDPLoginLogs():Promise<Array<pkg.RDPLoginInfo>>;

export function GetSensitiveFileInfo():Promise<Array<pkg.FileInfo>>;

export function GetShellHistory():Promise<Array<pkg.ShellHistory>>;

export function GetStartupItems():Promise<Array<pkg.StartupItem>>;

export function GetSystemInfo():Promise<pkg.SystemInfo>;

export function GetUserInfo():Promise<pkg.UserInfo>;

export function ParseEVTXFile(arg1:string):Promise<Array<pkg.EVTXEvent>>;

export function SaveCronTasks(arg1:Array<pkg.CronTask>):Promise<void>;

export function SaveEVTXFile(arg1:string):Promise<string>;

export function SaveFileMonitor(arg1:Array<pkg.FileInfo>):Promise<void>;

export function SaveLoginFailed(arg1:Array<pkg.LoginFailed>):Promise<void>;

export function SaveLoginSuccess(arg1:Array<pkg.LoginSuccess>):Promise<void>;

export function SaveNetworkConnections(arg1:Array<pkg.NetworkConn>):Promise<void>;

export function SaveNetworkInfo(arg1:pkg.NetworkInfo):Promise<void>;

export function SaveProcessInfo(arg1:Array<pkg.ProcInfo>):Promise<void>;

export function SaveRDPLogin(arg1:Array<pkg.RDPLoginInfo>):Promise<void>;

export function SaveShellHistory(arg1:Array<pkg.ShellHistory>):Promise<void>;

export function SaveStartupItems(arg1:Array<pkg.StartupItem>):Promise<void>;

export function SaveSystemInfo(arg1:pkg.SystemInfo):Promise<void>;

export function SaveUserInfo(arg1:pkg.UserInfo):Promise<void>;

export function SelectAndParseEVTXFile():Promise<Array<pkg.EVTXEvent>>;
