// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pkg} from '../models';

export function GetAllProcesses():Promise<Array<pkg.ProcInfo>>;

export function GetAllUsers():Promise<Array<pkg.SystemUser>>;

export function GetCronTasks():Promise<Array<pkg.CronTask>>;

export function GetLoginFailedRecords():Promise<Array<pkg.LoginFailed>>;

export function GetLoginSuccessRecords():Promise<Array<pkg.LoginSuccess>>;

export function GetNetworkConnections():Promise<Array<pkg.NetworkConn>>;

export function GetNetworkInfo():Promise<pkg.NetworkInfo>;

export function GetPatchInfo():Promise<Array<pkg.PatchInfo>>;

export function GetStartupItems():Promise<Array<pkg.StartupItem>>;

export function GetSystemInfo():Promise<pkg.SystemInfo>;

export function GetUserInfo():Promise<pkg.UserInfo>;
