// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllProcesses() {
  return window['go']['pkg']['App']['GetAllProcesses']();
}

export function GetAllUsers() {
  return window['go']['pkg']['App']['GetAllUsers']();
}

export function GetCronTasks() {
  return window['go']['pkg']['App']['GetCronTasks']();
}

export function GetLoginFailedRecords() {
  return window['go']['pkg']['App']['GetLoginFailedRecords']();
}

export function GetLoginSuccessRecords() {
  return window['go']['pkg']['App']['GetLoginSuccessRecords']();
}

export function GetNetworkConnections() {
  return window['go']['pkg']['App']['GetNetworkConnections']();
}

export function GetNetworkInfo() {
  return window['go']['pkg']['App']['GetNetworkInfo']();
}

export function GetRDPLoginLogs() {
  return window['go']['pkg']['App']['GetRDPLoginLogs']();
}

export function GetSensitiveFileInfo() {
  return window['go']['pkg']['App']['GetSensitiveFileInfo']();
}

export function GetShellHistory() {
  return window['go']['pkg']['App']['GetShellHistory']();
}

export function GetStartupItems() {
  return window['go']['pkg']['App']['GetStartupItems']();
}

export function GetSystemInfo() {
  return window['go']['pkg']['App']['GetSystemInfo']();
}

export function GetUserInfo() {
  return window['go']['pkg']['App']['GetUserInfo']();
}

export function ParseEVTXFile(arg1) {
  return window['go']['pkg']['App']['ParseEVTXFile'](arg1);
}

export function SaveCronTasks(arg1) {
  return window['go']['pkg']['App']['SaveCronTasks'](arg1);
}

export function SaveEVTXFile(arg1) {
  return window['go']['pkg']['App']['SaveEVTXFile'](arg1);
}

export function SaveFileMonitor(arg1) {
  return window['go']['pkg']['App']['SaveFileMonitor'](arg1);
}

export function SaveLoginFailed(arg1) {
  return window['go']['pkg']['App']['SaveLoginFailed'](arg1);
}

export function SaveLoginSuccess(arg1) {
  return window['go']['pkg']['App']['SaveLoginSuccess'](arg1);
}

export function SaveNetworkConnections(arg1) {
  return window['go']['pkg']['App']['SaveNetworkConnections'](arg1);
}

export function SaveNetworkInfo(arg1) {
  return window['go']['pkg']['App']['SaveNetworkInfo'](arg1);
}

export function SaveProcessInfo(arg1) {
  return window['go']['pkg']['App']['SaveProcessInfo'](arg1);
}

export function SaveRDPLogin(arg1) {
  return window['go']['pkg']['App']['SaveRDPLogin'](arg1);
}

export function SaveShellHistory(arg1) {
  return window['go']['pkg']['App']['SaveShellHistory'](arg1);
}

export function SaveStartupItems(arg1) {
  return window['go']['pkg']['App']['SaveStartupItems'](arg1);
}

export function SaveSystemInfo(arg1) {
  return window['go']['pkg']['App']['SaveSystemInfo'](arg1);
}

export function SaveUserInfo(arg1) {
  return window['go']['pkg']['App']['SaveUserInfo'](arg1);
}

export function SelectAndParseEVTXFile() {
  return window['go']['pkg']['App']['SelectAndParseEVTXFile']();
}
