// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllProcesses():Promise<Array<main.ProcInfo>>;

export function GetAllUsers():Promise<Array<main.SystemUser>>;

export function GetCronTasks():Promise<Array<main.CronTask>>;

export function GetLoginSuccessRecords():Promise<Array<main.LoginSuccess>>;

export function GetNetworkConnections():Promise<Array<main.NetworkConn>>;

export function GetNetworkInfo():Promise<main.NetworkInfo>;

export function GetPatchInfo():Promise<Array<main.PatchInfo>>;

export function GetStartupItems():Promise<Array<main.StartupItem>>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetUserInfo():Promise<main.UserInfo>;
