// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllProcesses() {
  return window['go']['main']['App']['GetAllProcesses']();
}

export function GetCronTasks() {
  return window['go']['main']['App']['GetCronTasks']();
}

export function GetNetworkInfo() {
  return window['go']['main']['App']['GetNetworkInfo']();
}

export function GetStartupItems() {
  return window['go']['main']['App']['GetStartupItems']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetUserInfo() {
  return window['go']['main']['App']['GetUserInfo']();
}
